In [10]:
import torch

### Создайте случайный FloatTensor размера 3x4x5

In [3]:
x=torch.FloatTensor(3,4,5)

In [4]:
x

tensor([[[ 9.6845e+24,  1.8611e+34,  4.2740e-43,  0.0000e+00, -1.7039e+27],
         [ 4.5580e-41, -1.7039e+27,  4.5580e-41,  1.8475e+20,  1.3585e-19],
         [ 4.0274e-11,  1.9146e-19,  2.3301e-09,  2.5491e+21,  1.3563e-19],
         [ 8.4828e-33,  1.3563e-19,  9.4500e+08,  7.9309e+34,  1.5788e-19]],

        [[ 2.7604e+20,  8.6769e-33,  1.6114e-19,  1.6020e-19,  7.4901e+11],
         [ 6.8901e+22,  3.1892e-09,  2.9479e+29,  1.7442e+28,  2.5171e-12],
         [ 5.4667e-11,  1.0736e+18,  1.8037e+28,  6.0644e-02,  3.1246e-15],
         [ 7.7073e+20,  2.2228e-15,  1.4582e-19,  7.5388e+17,  1.8559e-01]],

        [[ 1.0888e-32,  1.3563e-19,  6.3371e-10,  1.3585e-19,  2.3765e+20],
         [ 1.9316e-19,  2.3301e-09,  4.0786e+22,  1.3563e-19,  9.9368e-33],
         [ 3.0881e+29,  1.8916e+23,  7.1443e+31,  1.3496e-01,  1.8475e+20],
         [ 7.3162e+28,  1.7261e+25,  3.2139e-12,  1.1286e+27,  2.8405e+20]]])

### Выведите его форму (shape)

In [6]:
x.shape

torch.Size([3, 4, 5])

### Приведите его к форме 6 X 10

In [8]:
x6x10=torch.reshape(x, (6,10))

In [9]:
x

tensor([[[ 9.6845e+24,  1.8611e+34,  4.2740e-43,  0.0000e+00, -1.7039e+27],
         [ 4.5580e-41, -1.7039e+27,  4.5580e-41,  1.8475e+20,  1.3585e-19],
         [ 4.0274e-11,  1.9146e-19,  2.3301e-09,  2.5491e+21,  1.3563e-19],
         [ 8.4828e-33,  1.3563e-19,  9.4500e+08,  7.9309e+34,  1.5788e-19]],

        [[ 2.7604e+20,  8.6769e-33,  1.6114e-19,  1.6020e-19,  7.4901e+11],
         [ 6.8901e+22,  3.1892e-09,  2.9479e+29,  1.7442e+28,  2.5171e-12],
         [ 5.4667e-11,  1.0736e+18,  1.8037e+28,  6.0644e-02,  3.1246e-15],
         [ 7.7073e+20,  2.2228e-15,  1.4582e-19,  7.5388e+17,  1.8559e-01]],

        [[ 1.0888e-32,  1.3563e-19,  6.3371e-10,  1.3585e-19,  2.3765e+20],
         [ 1.9316e-19,  2.3301e-09,  4.0786e+22,  1.3563e-19,  9.9368e-33],
         [ 3.0881e+29,  1.8916e+23,  7.1443e+31,  1.3496e-01,  1.8475e+20],
         [ 7.3162e+28,  1.7261e+25,  3.2139e-12,  1.1286e+27,  2.8405e+20]]])

In [10]:
x6x10.shape

torch.Size([6, 10])

### Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

(Здесь я могу ошибаться, но я взял исходный вектор, так как он совпадает по размерности)

In [12]:
x*torch.LongTensor([1, 4, 2, 2, 1])

tensor([[[ 9.6845e+24,  7.4442e+34,  8.5479e-43,  0.0000e+00, -1.7039e+27],
         [ 4.5580e-41, -6.8154e+27,  9.1160e-41,  3.6950e+20,  1.3585e-19],
         [ 4.0274e-11,  7.6585e-19,  4.6603e-09,  5.0982e+21,  1.3563e-19],
         [ 8.4828e-33,  5.4253e-19,  1.8900e+09,  1.5862e+35,  1.5788e-19]],

        [[ 2.7604e+20,  3.4708e-32,  3.2228e-19,  3.2039e-19,  7.4901e+11],
         [ 6.8901e+22,  1.2757e-08,  5.8957e+29,  3.4884e+28,  2.5171e-12],
         [ 5.4667e-11,  4.2943e+18,  3.6074e+28,  1.2129e-01,  3.1246e-15],
         [ 7.7073e+20,  8.8914e-15,  2.9164e-19,  1.5078e+18,  1.8559e-01]],

        [[ 1.0888e-32,  5.4253e-19,  1.2674e-09,  2.7170e-19,  2.3765e+20],
         [ 1.9316e-19,  9.3205e-09,  8.1572e+22,  2.7126e-19,  9.9368e-33],
         [ 3.0881e+29,  7.5666e+23,  1.4289e+32,  2.6993e-01,  1.8475e+20],
         [ 7.3162e+28,  6.9044e+25,  6.4278e-12,  2.2573e+27,  2.8405e+20]]])

### Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

(А здесь снова взял вектор размерности 6х10, полученный ранее)

(x6x10 - это название переменной)

In [13]:
x6x10

tensor([[ 9.6845e+24,  1.8611e+34,  4.2740e-43,  0.0000e+00, -1.7039e+27,
          4.5580e-41, -1.7039e+27,  4.5580e-41,  1.8475e+20,  1.3585e-19],
        [ 4.0274e-11,  1.9146e-19,  2.3301e-09,  2.5491e+21,  1.3563e-19,
          8.4828e-33,  1.3563e-19,  9.4500e+08,  7.9309e+34,  1.5788e-19],
        [ 2.7604e+20,  8.6769e-33,  1.6114e-19,  1.6020e-19,  7.4901e+11,
          6.8901e+22,  3.1892e-09,  2.9479e+29,  1.7442e+28,  2.5171e-12],
        [ 5.4667e-11,  1.0736e+18,  1.8037e+28,  6.0644e-02,  3.1246e-15,
          7.7073e+20,  2.2228e-15,  1.4582e-19,  7.5388e+17,  1.8559e-01],
        [ 1.0888e-32,  1.3563e-19,  6.3371e-10,  1.3585e-19,  2.3765e+20,
          1.9316e-19,  2.3301e-09,  4.0786e+22,  1.3563e-19,  9.9368e-33],
        [ 3.0881e+29,  1.8916e+23,  7.1443e+31,  1.3496e-01,  1.8475e+20,
          7.3162e+28,  1.7261e+25,  3.2139e-12,  1.1286e+27,  2.8405e+20]])

In [14]:
y=torch.matmul(x6x10,torch.transpose(x6x10,0,1))

In [15]:
y

tensor([[       inf,        inf,        nan,        inf,       -inf,        nan],
        [       inf,        inf,        inf,        inf, 3.8543e+31,        inf],
        [       nan,        inf,        inf,        inf,        inf,        inf],
        [       inf,        inf,        inf,        inf, 1.1430e+19,        inf],
        [      -inf, 3.8543e+31,        inf, 1.1430e+19,        inf,        inf],
        [       nan,        inf,        inf,        inf,        inf,        inf]])

In [16]:
y.shape

torch.Size([6, 6])

### Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [14]:
from torch.autograd import Variable

In [34]:
point = torch.DoubleTensor([1., 0.5, 2.])

Здесь два варианта:
1. с тремя независимыми переменными (x, z, t)
2. с вектором переменных, каждая из координат которого, по сути, представляет независимую переменную

Вариант 1. С независимыми переменными x, z, t.

In [28]:
x=Variable(torch.DoubleTensor([1.]), requires_grad=True)
z=Variable(torch.DoubleTensor([0.5]), requires_grad=True)
t=Variable(torch.DoubleTensor([2.]), requires_grad=True)

In [29]:
y = pow(x,3)+z-75*t

In [30]:
y

tensor([-148.5000], dtype=torch.float64, grad_fn=<SubBackward0>)

In [31]:
y.backward()

Производная по каждой из переменных

In [32]:
print(x.grad)
print(z.grad)
print(t.grad)

tensor([3.], dtype=torch.float64)
tensor([1.], dtype=torch.float64)
tensor([-75.], dtype=torch.float64)


Вариант 2. Переменная-вектор p.

In [35]:
p = Variable(point, requires_grad=True)
o = pow(p[0], 3)+p[1]-75*p[2]

In [36]:
o.backward()

In [37]:
p.grad

tensor([  3.,   1., -75.], dtype=torch.float64)

В обоих вариантах производные по направлениям совпадают.

### Создайте единичный тензор размера 5x6

In [38]:
t = torch.ones(5,6)

In [39]:
t

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

### Переведите его в формат numpy

In [41]:
t_numpy = t.numpy()

In [42]:
t_numpy

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

### Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
### Посчитайте 

In [4]:
from torch import nn
from torch import optim

In [46]:
w1 = Variable(torch.rand(3), requires_grad=True)

Определение класса - не очень удачная попытка сделать функцию-класс, которая при вызове pred = f(x, w1) внутри обновляла бы значение градиента.
Но получилось более громоздко.

In [47]:
class custom_t:
    #w1 = Variable(torch.rand(3), requires_grad=True)
    
    @staticmethod
    def f(x, w1):
        return x**w1 - 2*x**2 + 5

In [127]:
x = Variable(torch.rand(3), requires_grad = True)
y = Variable(torch.rand(3), requires_grad = False)

In [128]:
print("w1: ", w1)

w1:  tensor([0.4486, 0.5936, 0.5186], requires_grad=True)


In [54]:
criterion = nn.MSELoss()

In [56]:
params = [w1]

In [57]:
optimizer = optim.SGD(params, lr=0.01)

In [67]:
x, y

(tensor([0.6800, 0.2177, 0.1886], requires_grad=True),
 tensor([0.5310, 0.2276, 0.3741]))

In [141]:
optimizer.zero_grad()
pred = custom_t.f(x, w1)
loss = criterion(pred, y)
print("loss: ", loss.item())

loss:  24.16851234436035


In [142]:
print(w1.grad)

tensor([0., 0., 0.])


In [143]:
loss.backward()

In [144]:
print(w1.grad)

tensor([-1.8828, -1.6401, -1.2886])


In [145]:
optimizer.step()

Определение функции, по сути, количества эпох оптимизации

In [146]:
def optimize_loop(n=100):
    for i in range(1,n):
        optimizer.zero_grad()
        pred = custom_t.f(x, w1)
        loss = criterion(pred, y)
        print("loss: ", loss.item())
        loss.backward()
        optimizer.step()
    

Использование функции с нужным количеством циклов

In [149]:
optimize_loop(1000)

loss:  18.380823135375977
loss:  18.38068962097168
loss:  18.38055419921875
loss:  18.380420684814453
loss:  18.38028907775879
loss:  18.380151748657227
loss:  18.380020141601562
loss:  18.3798885345459
loss:  18.3797550201416
loss:  18.379621505737305
loss:  18.379487991333008
loss:  18.37935447692871
loss:  18.37922477722168
loss:  18.37908935546875
loss:  18.37895965576172
loss:  18.37882423400879
loss:  18.378692626953125
loss:  18.37856101989746
loss:  18.378427505493164
loss:  18.378297805786133
loss:  18.378164291381836
loss:  18.378034591674805
loss:  18.377901077270508
loss:  18.377771377563477
loss:  18.377639770507812
loss:  18.37750816345215
loss:  18.377378463745117
loss:  18.37724494934082
loss:  18.377113342285156
loss:  18.376983642578125
loss:  18.376853942871094
loss:  18.376724243164062
loss:  18.37659454345703
loss:  18.376462936401367
loss:  18.376331329345703
loss:  18.376203536987305
loss:  18.376073837280273
loss:  18.375944137573242
loss:  18.37581443786621
los

loss:  18.33607292175293
loss:  18.335981369018555
loss:  18.33588218688965
loss:  18.335786819458008
loss:  18.335693359375
loss:  18.335596084594727
loss:  18.335500717163086
loss:  18.335405349731445
loss:  18.335309982299805
loss:  18.33521842956543
loss:  18.33512306213379
loss:  18.33502769470215
loss:  18.334932327270508
loss:  18.334836959838867
loss:  18.334741592407227
loss:  18.33464813232422
loss:  18.33455467224121
loss:  18.33445930480957
loss:  18.33436393737793
loss:  18.334272384643555
loss:  18.33417320251465
loss:  18.334081649780273
loss:  18.333988189697266
loss:  18.333892822265625
loss:  18.333799362182617
loss:  18.333703994750977
loss:  18.3336124420166
loss:  18.333518981933594
loss:  18.333425521850586
loss:  18.333330154418945
loss:  18.33323860168457
loss:  18.333145141601562
loss:  18.333051681518555
loss:  18.33296012878418
loss:  18.332862854003906
loss:  18.33277130126953
loss:  18.332677841186523
loss:  18.33258628845215
loss:  18.33249282836914
loss: 

loss:  18.303512573242188
loss:  18.303442001342773
loss:  18.303369522094727
loss:  18.30329704284668
loss:  18.303224563598633
loss:  18.30315399169922
loss:  18.303083419799805
loss:  18.303010940551758
loss:  18.302940368652344
loss:  18.30286979675293
loss:  18.302797317504883
loss:  18.302724838256836
loss:  18.302656173706055
loss:  18.302583694458008
loss:  18.30251121520996
loss:  18.302438735961914
loss:  18.302370071411133
loss:  18.30229949951172
loss:  18.302228927612305
loss:  18.302156448364258
loss:  18.302085876464844
loss:  18.30201530456543
loss:  18.301944732666016
loss:  18.301876068115234
loss:  18.30180549621582
loss:  18.301734924316406
loss:  18.301664352416992
loss:  18.301591873168945
loss:  18.30152130126953
loss:  18.301450729370117
loss:  18.301382064819336
loss:  18.30130958557129
loss:  18.301240921020508
loss:  18.301170349121094
loss:  18.30109977722168
loss:  18.3010311126709
loss:  18.30095863342285
loss:  18.30088996887207
loss:  18.300819396972656
